require "user.options"
require "user.globals"
require "user.keymaps"
require "user.plugins"

require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.hop"
require "user.gitsigns"
require "user.trouble"
require "user.bufferline"
require "user.nvim-comment"
require "user.neoscroll"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"

