# All SpaceVim option below [option] section
[options]
  colorscheme = "halcyon"
  colorscheme_bg = "dark"
  enable_guicolors = true

  # Layer: core#statusline
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_statusline_mode = true

  # Layer: core#tabline
  enable_tabline_filetype_icon = true

  # Layer: autocomplete
  autocomplete_method = 'coc'

# Autocomplete
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

# Improved default options
[[layers]]
  name = 'default'

# Fuzzy finder
[[layers]]
  name = 'fzf'

# Git support
[[layers]]
  name = 'git'

# Create terminal sessions inside Neovim
[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

# Add extra Vim tools
[[layers]]
  name = 'tools'

# Language support
[[layers]]
  name = 'lang#javascript'
  auto_fix = true
# [[layers]]
#   name = 'lang#typescript'
[[layers]]
  name = 'lang#python'
[[layers]]
  name = 'lang#go'
[[layers]]
  name = 'lang#html'
[[layers]]
  name = 'lang#powershell'
[[layers]]
  name = 'lang#markdown'

# Custom theme https://github.com/NieTiger/halcyon-neovim
[[custom_plugins]]
  repo = "https://github.com/NieTiger/halcyon-neovim"
  merged = false
# Custom icons https://github.com/ryanoasis/vim-devicons

[[custom_plugins]]
   repo = "ryanoasis/vim-devicons"
   # note: you need to disable merged feature
   merged = false

