#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "halcyon"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filemanager = "defx"

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

# Enable fuzzy finder (another fine option is 'unite')
[[layers]]
    name = "denite"

# Custom theme https://github.com/mhartington/oceanic-next
[[custom_plugins]]
    repo = "mhartington/oceanic-next"
    merged = 0

# Custom theme https://github.com/drewtempelmeyer/palenight.vim
[[custom_plugins]]
    repo = "https://github.com/drewtempelmeyer/palenight.vim"
    merged = false

# Custom theme https://github.com/NieTiger/halcyon-neovim
[[custom_plugins]]
  repo = "https://github.com/NieTiger/halcyon-neovim"
  merged = false

# Custom theme https://github.com/KeitaNakamura/neodark.vim
[[custom_plugins]]
  repo = "https://github.com/KeitaNakamura/neodark.vim"
  merged = false

# Custom theme https://github.com/ghifarit53/tokyonight-vim
[[custom_plugins]]
  repo = "https://github.com/ghifarit53/tokyonight-vim" 
  merged = 0

# Custom icons https://github.com/ryanoasis/vim-devicons
[[custom_plugins]]
   repo = "ryanoasis/vim-devicons"
   # note: you need to disable merged feature
   merged = false

# This repo throws errors when Neovim open
# Custom icons https://github.com/kristijanhusak/defx-icons
#    repo = "https://github.com/kristijanhusak/defx-icons"
#   merged = false

# Language support
[[layers]]
    name = "lang#javascript"

[[layers]]
    name = "lang#typescript"

[[layers]]
    name = "lang#python"
